### ISSUE TITLE
highline with thor gem

### ISSUE THREAD

**Issue by hiroyuki-sato** [JEG2/highline#144] opened 2015-06-30 06:02 UTC
Hello.

A little off topic.
Does anyone have any good idea to use highline with thor gem?

The following code does not show default value if I use ``ask`` method inside thor method.

```ruby
require 'highline/import'
require 'thor'

class Hoge < Thor
  desc "highline_test","highline input test"
  def highline_test
    country = ask("country?"){ |q| q.default = "none" }
  end
end
Hoge.start

country = ask("country?"){ |q| q.default = "none" }
```

Execute result.

```ruby
ruby b.rb highline_test
country?         # <-- insdie thor
country?  |none| # <-- outside thor
```

Environment

* OSX: 10.10.3
* ruby: 2.2.1
* thor: 0.19.1
* highline: 1.7.2

--
Hiroyuki Sato.

**Comment by abinoam** [comment] 2015-06-30 15:48
こんにちは 

Dear @hiroyuki-sato,

The issue is being caused by a name collision.
Thor has also a method called __ask__.
http://www.rubydoc.info/github/wycats/thor/Thor/Shell/Basic#ask-instance_method

I could catch the collision with the following
```ruby
require 'highline/import'
require 'thor'

class Hoge < Thor
  desc "highline_test","highline input test"
  def highline_test
    puts method(:ask).source_location.inspect
  end
end
Hoge.start

puts method(:ask).source_location.inspect
```

It outputs
```ruby
# Inside thor
["/Users/abinoam/.rvm/gems/ruby-2.2.2@hl_144/gems/thor-0.19.1/lib/thor/shell.rb", 58]
# Outside thor
["/Users/abinoam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/forwardable.rb", 181]
```

You should create a HighLine instance by yourself and call #ask on it to avoid name collision.
And, if you're going this way, you will not need to require 'highline/import', just require 'highline'.

Like this:
```ruby
require 'highline'
require 'thor'

class Hoge < Thor
  desc "highline_test","highline input test"
  def highline_test
    cli = HighLine.new
    country = cli.ask("country?"){ |q| q.default = "none" }
  end
end
Hoge.start
```
See also: https://github.com/erikhuda/thor/issues/108

Thank you for reporting this. This issue will surely be useful for others that face this on the future.
Give us some feedback if that worked for you so we could close the issue.

**Comment by hiroyuki-sato** [comment] 2015-06-30 23:18
こんにちは @abinoam 
どうもありがとうございます。

Thank you for your replying.

It worked as I expected.
Thanks.

**Comment by abinoam** [comment] 2015-07-01 00:11
You're welcome.

**Closed by abinoam** 2015-07-01 00:11 UTC
