### ISSUE TITLE
HighLine#ask crashes on suspend

### ISSUE THREAD

**Issue by mickeyreiss** [JEG2/highline#96] opened 2013-10-30 19:49 UTC
If the user suspends the program while being `HighLine#ask`'ed a question, HighLine occasionally crashes. Ideally, suspending (i.e. `SIGSTOP`) should be supported.

```
Edit CHANGELOG?
^Z
[1]  + 39240 suspended  rake release
➜  myproject git:(master) git tag -l
➜  myproject git:(master) fg
[1]  + 39240 continued  rake release
rake aborted!
Input/output error - <STDIN>
/Users/mickeyreiss/.rvm/gems/ruby-1.9.3-p448@myproject/gems/highline-1.6.20/lib/highline.rb:863:in `eof?'
/Users/mickeyreiss/.rvm/gems/ruby-1.9.3-p448@myproject/gems/highline-1.6.20/lib/highline.rb:863:in `get_line'
/Users/mickeyreiss/.rvm/gems/ruby-1.9.3-p448@myproject/gems/highline-1.6.20/lib/highline.rb:885:in `get_response'
/Users/mickeyreiss/.rvm/gems/ruby-1.9.3-p448@myproject/gems/highline-1.6.20/lib/highline.rb:260:in `ask'
/Users/mickeyreiss/.rvm/gems/ruby-1.9.3-p448@myproject/gems/highline-1.6.20/lib/highline.rb:223:in `agree'
/Users/mickeyreiss/code/myproject/Rakefile:47:in `block in <top (required)>'
Tasks: TOP => release
(See full trace by running task with --trace)
```

OS X 10.8.4/zsh 4.3.11

**Comment by abinoam** [comment] 2015-02-02 14:09
I couldn't reproduce the crash. But in a macosx 10.9.4 and bash 4.3 Ctrl-Z in the middle of the input has unpredictable consequences on what #ask returns. Need futher investigation.

**Comment by abinoam** [comment] 2015-03-08 02:12
Just taking note of this gist. Perhaps relevant.
https://gist.github.com/zdennis/3a0b685047ac086725b0

**Comment by zdennis** [comment] 2015-03-08 21:17
@abinoam, thanks for looping me in here. This may very well be related. When you say:

>  Ctrl-Z in the middle of the input has unpredictable consequences on what #ask returns

Can you describe what you're seeing? Is it that one or more characters may be often be missing?

**Comment by abinoam** [comment] 2015-03-09 00:01
Hi @zdennis 

I have tried again with HighLine 1.7.1
A simple #ask as in:
```ruby
#!/usr/bin/env ruby

require 'highline/import'

anything = ask("Anything?  ")
puts "You told #{anything}"
```

If you type something, then CTRL-Z, do something, and then ```fg```, then you type another thing and then type enter.
HighLine just "drop" the first 'typing' and then shows you the last one (the one that you typed after the __fg__).

Well, but there's the "readline" mode, the noecho mode and etc. that I didn't tested.

So, IMHO, we shouldn't put too much (I mean any) effort in fixing this _now_.
HighLine will soon be under a major refactor.
So, with a _cleaner_ code base I think it would be easy for you to hunt this bug (in case it persists).

**Comment by abinoam** [comment] 2023-01-07 10:31
I've just tested for this behavior again with Ruby 3.2 and ubuntu 22.04.

The problem happens with "pure" `gets`

Try

```bash
ruby -e "p gets"
```

First type "first"
Then hit `ctrl-Z`
Then type "second" and hit `<enter>`
The returned string will be only "second"

I think suspending the process is flushing the input buffer.
If it affects `Kernel#gets` it's probably the intended behavior to flush the input buffer when suspending, but I'm not sure.

**Comment by abinoam** [comment] 2023-01-07 10:38
I've just tried with bash and the behavior is the same

```bash
#!/bin/bash

printf "Type: "

read astring

echo $astring
```

I'm closing this as a "non bug" meanwhile, but feel free to comment or reopen it @mickeyreiss if you want to discuss it any further.
Sorry for taking so long to answer this issue. I'm taking some time now to clean up them all these days.

**Closed** 2023-01-07 10:39 UTC
Labels: bug
