### ISSUE TITLE
default value has to be a string

### ISSUE THREAD

**Issue by branch14** [JEG2/highline#233] opened 2018-06-07 07:23 UTC
I'm not sure this is intentional.

The default value for ask has to be a string, if it is an integer, it is silently ignored. 

Tested with v1.7.10

This was not the case prior to v1.7.0

Demo:

```
require 'highline'                                                                                        
                                                                                                          
cli = HighLine.new                                                                                        
                                                                                                          
cli.ask("Default string works", Integer) { |q| q.default = "123" }                                        
cli.ask("Default integer doesn't", Integer) { |q| q.default = 456 }
```

**Comment by abinoam** [comment] 2018-06-10 04:00
Hi @branch14 ,

I don't plan to patch 1.7-stable branch anymore.
I couldn't reproduce the issue at 2.0 branch.

**Comment by abinoam** [comment] 2018-06-11 11:54
@branch14 today we have officially released 2.0.0 version!
I'll close this issue, but feel free to reopen it if you think it's necessary.

Thank you very much for your feedback! 👍

**Comment by branch14** [comment] 2018-06-13 19:22
Thank you for your work on highline. I never tried the 2.0 branch, but now that it has been release I totally will. :)

**Comment by abinoam** [comment] 2018-06-13 19:37
Thank you! I hope it work well. Give me a feedback as soon as you tested it 👍

**Comment by branch14** [comment] 2018-06-14 07:12
I tested it and unfortunately I found the same issue in 2.0.0

Luckily the work around still works. :)

Here is how to reproduce it:

```
#!/usr/bin/env ruby                                                                                                                                                                                                 
                                                                                                                                                                                                                    
require 'highline'                                                                                                                                                                                                  
                                                                                                                                                                                                                    
h = HighLine.new                                                                                                                                                                                                    
                                                                                                                                                                                                                    
h.ask("Default shows if it is a string: ", String) { |q| q.default = "I am a string" }                                                                                                                              
                                                                                                                                                                                                                    
h.ask("Default doesn't show if it is an int: ", Integer) { |q| q.default = 42 }                                                                                                                                     
                                                                                                                                                                                                                    
h.ask("But strangly this works: ", Integer) { |q| q.default = "42" }                                                                                                                                                
                                                                                                                                                                                                                    
# % ruby test.rb                                                                                                                                                                                                    
# Default shows if it is a string: |I am a string|                                                                                                                                                                  
# Default doesn't show if it is an int:                                                                                                                                                                             
# But strangly this works: |42|
```

**Comment by abinoam** [comment] 2018-06-19 00:35
I've reopened the issue.
Could you clone the repo and ```run rake acceptance``` and post the results here?

**Comment by abinoam** [comment] 2018-06-19 00:38
It was correctly reproduced in my enviroment.

**Comment by abinoam** [comment] 2018-06-19 01:03
In a quick look what I see is...

Default value is about the **answer gathering** part. We should always receive a string by keyboard, although we could have any kind of object as default. This could be useful for several scenarios by passing as default a more meaningful object than `nil`.

That `Integer` is more about **coercion**.

I can see that Highline is doing a type check at this part

```ruby
    def build_responses(message_source = answer_type)
      append_default if [::String, Symbol].include? default.class

      new_hash = build_responses_new_hash(message_source)
      # Update our internal responses with the new hash
      # generated from the message source
      @internal_responses = @internal_responses.merge(new_hash)
    end
```

I would prefer to just cast it into a String and check if it is empty or not (to avoid placing two bars side by side without any content inside it. Like ||).

But, any object in Ruby has a string representation by default. And, at that case that I pass bare object I could have the weird result like this:
```"Question:  |#<Object:0xXXXXXX>|  "```

From: TestHighLine#test_default_with_non_String_objects [/Users/abinoam/src/highline/test/test_highline.rb:834

So, perhaps sticking with the type checking thing, although not being the more flexible way, solves your problem without any great change at the behaviour of HighLine.

**Comment by abinoam** [comment] 2018-06-27 01:07
I may agree with you. But this breaks the current behaviour. We can discuss this to come in a major release.

For now, I think we can ammend the type checking part adding Integer to the list.
This will solve for your specific case without any major break.
What do you think about this?

**Comment by abinoam** [comment] 2018-09-03 15:08
Hi @branch14 what do you think about my last comment 👆

**Comment by branch14** [comment] 2018-09-03 16:41
I fully concur. I'm sorry I didn't mean to let you hanging.

**Comment by abinoam** [comment] 2023-01-01 17:05
Hi @branch14 

Sorry for taking so long.
I'll add the requested behavior at the same time adding a switch do disable it.
So people can easily transition between the to behaviors (showing or not showing the Question#default value hint).
Code is ready, opening a PR.

**Comment by abinoam** [comment] 2023-01-01 17:06
I'll have to do a major release as this is a breaking change.

**Closed** 2023-01-01 17:43 UTC
Labels: feature request
