### ISSUE TITLE
NoMethodError: undefined method `length' for #<HighLine::Question:0x007f6c2240fb38>

### ISSUE THREAD

**Issue by derrickmar** [JEG2/highline#151] opened 2015-08-12 22:37 UTC
I tried to investigate why this is happening but couldn't figure it out. I'm I doing something wrong here?

I don't even see where length is ever called in the source code.

```ruby
num_frqs_prompt = HighLine::Question.new(
  "How many additional FreeResponseQuestions would you like to add?  ",
  Integer
)
num_frqs_prompt.default = 10
ask(num_frqs_prompt) # This raises error above.
```

**Comment by abinoam** [comment] 2015-08-12 22:48
Hi @derrick,

I couldn't reproduce the error in 2.0.0.pre.develop.2 version.
And I've had another error in 1.7.3 (TypeError).

What version and OS are you in?

**Comment by abinoam** [comment] 2015-08-12 23:41
Hi @derrickmar 

You could also try to let HighLine#ask handle things to you.

```ruby
#!/usr/bin/env ruby

require 'highline/import'

puts "Using HighLine::VERSION #{HighLine::VERSION}"
puts "Using #{RUBY_DESCRIPTION}"

statement = "How many additional FreeResponseQuestions would you like to add?  "
answer = ask(statement, Integer) do |q|
  q.default = 10
end
puts answer

```

Let us know if it worked for you. I would be glad to help you make it work.

**Comment by derrickmar** [comment] 2015-08-13 02:48
Hey @abinoam yes that is what I reverted to. I was using version ```highline (1.6.21)```

Mac OSX Yosemite

**Comment by derrickmar** [comment] 2015-08-13 02:49
It might be worth noting that we have an ActiveRecord model also named ```Question```.

I don't see how this will break things. But the script I ran above was after I loaded our rails environment

**Comment by abinoam** [comment] 2015-08-13 08:55
You could simply use ```HighLine::Question``` namespaced in order to avoid name collisions.
And more, you can ```require 'highline'``` (not 'highline/import') and it will not make any changes to the main namespace. But you'll have to have a reference to a HighLine instance. Easy as bellow:
```ruby
require 'highline'

cli = HighLine.new
cli.ask "How old are you?", Integer
```

Just to be sure, then is it solved for you? 
Upgrading to a newer HighLine version made it work in your environment?
Can we close the issue?

Thanks for any feedback.

**Comment by abinoam** [comment] 2015-09-05 04:02
Hi @derrickmar, 
Could you confirm it solved for you?

**Comment by abinoam** [comment] 2015-09-18 02:51
Closing as stale. If @derrickmar has any news he can reopen the issue.

**Closed by abinoam** 2015-09-18 02:51 UTC
