### ISSUE TITLE
Line wrapping when running highline

### ISSUE THREAD

**Issue by KrauseFx** [JEG2/highline#138] opened 2015-04-18 07:12 UTC
I'm writing regarding an issue with all nomad tools (https://github.com/nomad/shenzhen/issues/246) and all [fastlane](https://fastlane.tools).

Both tool chains make use of highline for both parsing user input using `commander` and for asking users for missing information.

Just recently we ran into issues with line wrapping. When running the following in `irb` (same behaviour as when running directly in the tools):

```ruby
s2.0.0-p481 :001 > ask("hi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi there")
hi therehi therehi therehi therehi therehi therehi therehi therehi therehi
therehi therehi therehi therehi therehi there
```

I can't tell which version introduced the error. Is it an error on our side?

**Comment by JEG2** [comment] 2015-04-18 14:31
@abinoam Could you investigate this when you have a chance?

**Comment by abinoam** [comment] 2015-04-19 03:33
Hi @KrauseFx  and @JEG2 

I think it's probably a regression of #131.
It was fixed for the "develop" branch here #136 (but not for master branch... my bad!)

I'll reapply and issue a PR now.

**Comment by abinoam** [comment] 2015-04-19 03:47
@KrauseFx, could you check if the PR #139 fixes the issue? Before @JEG2 makes a new release?
(I'm not able to reproduce neither the fail nor the fix by now).

You could just clone the git repo and run "rake install".

**Comment by abinoam** [comment] 2015-04-22 03:21
Confirmed fix at:
https://github.com/nomad/shenzhen/issues/246#issuecomment-94321396
https://github.com/JEG2/highline/pull/139#issuecomment-94304806
Mergerd at #139
Closing.

**Closed by abinoam** 2015-04-22 03:21 UTC
