### ISSUE TITLE
serializing HighLine::String to yaml produces strange results

### ISSUE THREAD

**Issue by viking** [JEG2/highline#69] opened 2013-03-07 00:33 UTC
Consider:

    require 'highline'
    require 'yaml'

    hl = HighLine.new
    x = hl.ask("foo: ")
    puts x.to_yaml

Output:

    foo: bar
    --- !ruby/string:HighLine::String |-
      YmFy

I'm using ruby 2.0.0-p0.

**Comment by abinoam** [comment] 2015-02-04 00:06
I couldn't reproduce the issue anymore. I think it was fixed in YAML. Added a test on 1c6a8fa to serve as guard against any future regression.

**Comment by JEG2** [comment] 2015-02-04 00:44
Perfect.

**Closed** 2015-02-04 00:44 UTC
